### ISSUE TITLE
when we run "cargo contract build" then we face this error. Please provide the solution.

### ISSUE THREAD

**Issue by RaoMusharraf** [1010adigupta/ink-Stable-Coin#2]
ERROR: Error invoking `cargo metadata` for Cargo.toml

Caused by:
    `cargo metadata` exited with an error:     Updating crates.io index
        Updating git repository `https://github.com/Brushfam/openbrush-contracts`
    error: failed to get `openbrush` as a dependency of package `stable_coin_contract v4.0.0-beta.1 (/home/rao/Documents/FaisalBhai/ink-Stable-Coin/contracts/stable-coin)`
    
    Caused by:
      failed to load source for dependency `openbrush`
    
    Caused by:
      Unable to update https://github.com/Brushfam/openbrush-contracts?tag=v4.0.0-beta
    
    Caused by:
      failed to find tag `v4.0.0-beta`
    
    Caused by:
      reference 'refs/remotes/origin/tags/v4.0.0-beta' not found; class=Reference (4); code=NotFound (-3)

**Comment by harry2855** [comment]
Try changing 
```
openbrush = { tag = "v4.0.0-beta", git = "https://github.com/Brushfam/openbrush-contracts", default-features = false, features = ["ownable", "psp22"] }
```
to
```
openbrush = { branch = "main", git = "https://github.com/Brushfam/openbrush-contracts", default-features = false, features = ["ownable", "psp22"] }
```
in cargo.toml of stable-coin folder
